Category.create([

{name:"19th c American",dim:"community"},
{name:"Augustan",dim:"community"},
{name:"Edwardian",dim:"community"},
{name:"Late 18th c",dim:"community"},
{name:"Medieval",dim:"community"},
{name:"Milton",dim:"community"},
{name:"Modernist",dim:"community"},
{name:"Postmodernist",dim:"community"},
{name:"Renaissance",dim:"community"},
{name:"Restoration",dim:"community"},
{name:"Romantic",dim:"community"},
{name:"Victorian",dim:"community"},
{name:"Drama",dim:"form"},
{name:"Poetry",dim:"form"},
{name:"Prose",dim:"form"},
{name:"Bildungsroman",dim:"genre"},
{name:"Comedy",dim:"genre"},
{name:"Confessional",dim:"genre"},
{name:"Devotional",dim:"genre"},
{name:"Diary",dim:"genre"},
{name:"Epic",dim:"genre"},
{name:"Misc",dim:"genre"},
{name:"Narrative verse",dim:"genre"},
{name:"Nonfiction",dim:"genre"},
{name:"Novel",dim:"genre"},
{name:"Picaresque",dim:"genre"},
{name:"Plain style",dim:"genre"},
{name:"Polemic",dim:"genre"},
{name:"Romance",dim:"genre"},
{name:"Satire",dim:"genre"},
{name:"Short story",dim:"genre"},
{name:"Thriller",dim:"genre"},
{name:"Low",dim:"standing"},
{name:"Middle",dim:"standing"},
{name:"Upper",dim:"standing"}
# ,
# {name:"All",dim:"community"},
# {name:"All",dim:"form"},
# {name:"All",dim:"genre"},
# {name:"All",dim:"standing"}

])
