Category.create([

  {category_id:21,name:"19th c American",dim:"community"},
  {category_id:22,name:"Augustan",dim:"community"},
  {category_id:29,name:"Edwardian",dim:"community"},
  {category_id:20,name:"Late 18th c",dim:"community"},
  {category_id:30,name:"Medieval",dim:"community"},
  {category_id:27,name:"Milton",dim:"community"},
  {category_id:25,name:"Modernist",dim:"community"},
  {category_id:28,name:"Postmodernist",dim:"community"},
  {category_id:19,name:"Renaissance",dim:"community"},
  {category_id:24,name:"Restoration",dim:"community"},
  {category_id:23,name:"Romantic",dim:"community"},
  {category_id:26,name:"Victorian",dim:"community"},
  {category_id:18,name:"Drama",dim:"form"},
  {category_id:16,name:"Poetry",dim:"form"},
  {category_id:17,name:"Prose",dim:"form"},
  {category_id:1,name:"Bildungsroman",dim:"genre"},
  {category_id:2,name:"Comedy",dim:"genre"},
  {category_id:3,name:"Diary",dim:"genre"},
  {category_id:4,name:"Epic",dim:"genre"},
  {category_id:5,name:"Essay",dim:"genre"},
  {category_id:6,name:"Letters",dim:"genre"},
  {category_id:7,name:"Lyric",dim:"genre"},
  {category_id:8,name:"Misc",dim:"genre"},
  {category_id:9,name:"Nonfiction",dim:"genre"},
  {category_id:10,name:"Novel",dim:"genre"},
  {category_id:11,name:"Picaresque",dim:"genre"},
  {category_id:12,name:"Romance",dim:"genre"},
  {category_id:13,name:"Satire",dim:"genre"},
  {category_id:14,name:"Short Story",dim:"genre"},
  {category_id:15,name:"Thriller",dim:"genre"},
  # {category_id:33,name:"Low",dim:"standing"},
  # {category_id:32,name:"Middle",dim:"standing"},
  {category_id:31,name:"Upper Class",dim:"standing"},
  {category_id:34,name:"Middle/Lower Classes",dim:"standing"}


])
