Category.create([
{name: "Devotional" },
{name: "Misc" },
{name: "Nonfiction" },
{name: "Comedy" },
{name: "Thriller" },
{name: "Picaresque" },
{name: "Plain style" },
{name: "Confessional" },
{name: "Narrative verse" },
{name: "Romance" },
{name: "Satire" },
{name: "Epic" },
{name: "Novel" },
{name: "Polemic" },
{name: "Bildungsroman" },
{name: "Short story" },
{name: "Diary" },
{name: "Poetry" },
{name: "Prose" },
{name: "Drama" },
{name: "Renaissance" },
{name: "Late 18th c" },
{name: "19th c American" },
{name: "Augustan" },
{name: "Romantic" },
{name: "Restoration" },
{name: "Modernist" },
{name: "Victorian" },
{name: "Milton" },
{name: "Postmodernist" },
{name: "Edwardian" },
{name: "Medieval" },
{name: "Upper" },
{name: "Middle" },
{name: "Low" }
])