Genre.create([
{name: "Devotional" },
{name: "Misc" },
{name: "Nonfiction" },
{name: "Comedy" },
{name: "Thriller" },
{name: "Picaresque" },
{name: "Plain style" },
{name: "Confessional" },
{name: "Narrative verse" },
{name: "Romance" },
{name: "Satire" },
{name: "Epic" },
{name: "Novel" },
{name: "Polemic" },
{name: "Bildungsroman" },
{name: "Short story" },
{name: "Diary" },
])