Placename.create([
  {"placename_id":30001,"placename":"22 Orchard Street, Marylebone"},
  {"placename_id":30002,"placename":"Albemarle St., Piccadilly"},
  {"placename_id":30003,"placename":"Bruton St., Mayfair"},
  {"placename_id":30004,"placename":"10 Hertford St"},
  {"placename_id":30005,"placename":"37 St. James's Place"},
  {"placename_id":30006,"placename":"9 St. George St."},
  {"placename_id":30007,"placename":"14 Savile Row, Mayfair"},
  {"placename_id":30008,"placename":"Took's Court, Holborn"},
  {"placename_id":30009,"placename":"Woodstock St., Mayfair"},
  {"placename_id":30010,"placename":"6 Great Castle Street"},
  {"placename_id":30011,"placename":"Boswell Court, Holborn"},
  {"placename_id":30012,"placename":"Greenwich"},
  {"placename_id":30013,"placename":"17 Gough Square"},
  {"placename_id":30014,"placename":"Cheshire Cheese tavern"},
  {"placename_id":30015,"placename":"Mitre Tavern on Fleet Street"},
  {"placename_id":30016,"placename":"Staple Inn"},
  {"placename_id":30017,"placename":"4 Inner Temple Lane, Gray's Inn"},
  {"placename_id":30018,"placename":"7 Johnson's Court"},
  {"placename_id":30019,"placename":"Bolt Court"},
  {"placename_id":30020,"placename":"a traffic island in the middle of Fleet Street"},
  {"placename_id":30021,"placename":"Downing Street"},
  {"placename_id":30025,"placename":"Chelsea"},
  {"placename_id":30026,"placename":"Upper Thames Street"},
  {"placename_id":30027,"placename":"the Savoy Palace"},
  {"placename_id":30028,"placename":"Aldgate High Street"},
  {"placename_id":30029,"placename":"Westminster Abbey"},
  {"placename_id":30030,"placename":"Salisbury Square, just off Fleet Street"},
  {"placename_id":30031,"placename":"St. Margaret's church, Westminster"},
  {"placename_id":30032,"placename":"Seething Lane"},
  {"placename_id":30033,"placename":"the Thames"},
  {"placename_id":30034,"placename":"Southwark"},
  {"placename_id":30035,"placename":"14  Buckingham Street"},
  {"placename_id":30036,"placename":"Clapham Common"},
  {"placename_id":30037,"placename":"St. Olaf's"},
  {"placename_id":30038,"placename":"Plough Court"},
  {"placename_id":30039,"placename":"Hammersmith"},
  {"placename_id":30040,"placename":"Cleveland Court near St. James's Palace"},
  {"placename_id":30041,"placename":"110 Chiswick Lane in Chiswick"},
  {"placename_id":30042,"placename":"Twickenham"},
  {"placename_id":30043,"placename":"Old Palace Yard, Westminster"},
  {"placename_id":30044,"placename":"St. Margaret's"},
  {"placename_id":30045,"placename":"Bread Street"},
  {"placename_id":30046,"placename":"Mermaid Tavern"},
  {"placename_id":30047,"placename":"Thavies Inn"},
  {"placename_id":30048,"placename":"Lincoln's Inn"},
  {"placename_id":30050,"placename":"Savoy Way"},
  {"placename_id":30051,"placename":"Drury Lane"},
  {"placename_id":30053,"placename":"St. Paul's Cathedral"},
  {"placename_id":30054,"placename":"St. Bride's"},
  {"placename_id":30055,"placename":"Aldersgate-Street"},
  {"placename_id":30056,"placename":"17 Barbican"},
  {"placename_id":30058,"placename":"49 Charing Cross Lane"},
  {"placename_id":30059,"placename":"Whitehall"},
  {"placename_id":30060,"placename":"Petty France"},
  {"placename_id":30061,"placename":"Bartholomew Close, West Smithfield"},
  {"placename_id":30062,"placename":"Red Lion Square, Holborn"},
  {"placename_id":30063,"placename":"Jewin St. off Aldersgate St."},
  {"placename_id":30064,"placename":"125 Bunhill Row"},
  {"placename_id":30065,"placename":"the Guildhall"},
  {"placename_id":30066,"placename":"St. Giles Without Cripplegate"},
  {"placename_id":30067,"placename":"Broad Street and Marshall Street in Soho"},
  {"placename_id":30068,"placename":"Golden Square"},
  {"placename_id":30069,"placename":"Battersea Parish Church"},
  {"placename_id":30070,"placename":"Green St."},
  {"placename_id":30071,"placename":"27 Broad St., Soho"},
  {"placename_id":30072,"placename":"28 Poland St."},
  {"placename_id":30073,"placename":"Hercules Buildings, Lambeth"},
  {"placename_id":30074,"placename":"17 South Molton St., Mayfair"},
  {"placename_id":30075,"placename":"3 Fountain Court"},
  {"placename_id":30076,"placename":"Bunhill Fields Burial Ground"},
  {"placename_id":30077,"placename":"139 Long Acre, Covent Garden"},
  {"placename_id":30078,"placename":"6 Suffolk St."},
  {"placename_id":30079,"placename":"12 Rathbone Place, Fitzrovia"},
  {"placename_id":30082,"placename":"St. Andrew's Church"},
  {"placename_id":30083,"placename":"Petty France, Westminster"},
  {"placename_id":30084,"placename":"Southampton Coffee House"},
  {"placename_id":30085,"placename":"Chapel St."},
  {"placename_id":30086,"placename":"10 Down St."},
  {"placename_id":30087,"placename":"40 Half Moon St."},
  {"placename_id":30088,"placename":"3 Bouverie St., Piccadill"},
  {"placename_id":30089,"placename":"6 Frith Street, Soho"},
  {"placename_id":30090,"placename":"St. Anne's"},
  {"placename_id":30091,"placename":"Gordon's Hotel on Albemarle St."},
  {"placename_id":30092,"placename":"Batt's Hotel in Jermyn St."},
  {"placename_id":30093,"placename":"Reddish's Hotel in St. James's"},
  {"placename_id":30094,"placename":"Cox's Hotel in Jermyn St."},
  {"placename_id":30095,"placename":"Long's Hotel on Clifford St"},
  {"placename_id":30096,"placename":"8 St James's Street"},
  {"placename_id":30097,"placename":"4 Bennet Street"},
  {"placename_id":30098,"placename":"Albany"},
  {"placename_id":30099,"placename":"13 Piccadilly Terrace"},
  {"placename_id":30102,"placename":"76 Cheapside"},
  {"placename_id":30103,"placename":"1 Well Walk in Hampstead"},
  {"placename_id":30104,"placename":"Keats Grove in Hampstead"},
  {"placename_id":30105,"placename":"2, Wesleyan Place"},
  {"placename_id":30106,"placename":"Poland Street, in Soho"},
  {"placename_id":30107,"placename":"St. George's Church, St. James's"},
  {"placename_id":30108,"placename":"15 Old Bond Street in Piccadilly"},
  {"placename_id":30109,"placename":"Southampton Buildings"},
  {"placename_id":30110,"placename":"Gray's Inn Garden"},
  {"placename_id":30111,"placename":"Nelson Square"},
  {"placename_id":30115,"placename":"26 Marchmont St."},
  {"placename_id":30116,"placename":"Cannon and Queen Victoria Streets"},
  {"placename_id":30118,"placename":"119 Great Russell Street"},
  {"placename_id":30119,"placename":"Cheyne Row"},
  {"placename_id":30120,"placename":"Gloucester Place, Marylebone"},
  {"placename_id":30121,"placename":"Wimpole Street"},
  {"placename_id":30122,"placename":"Marylebone Parish Church"},
  {"placename_id":30123,"placename":"13 Dorset Street"},
  {"placename_id":30124,"placename":"Wimpole St."},
  {"placename_id":30126,"placename":"16 Young Street"},
  {"placename_id":30127,"placename":"36 Onslow Square in South Kensington"},
  {"placename_id":30128,"placename":"2 Palace Green"},
  {"placename_id":30129,"placename":"58 Welbeck St, Marylebone"},
  {"placename_id":30130,"placename":"13 Dorset St"},
  {"placename_id":30131,"placename":"19 Warwick Crescent, Paddington"},
  {"placename_id":30132,"placename":"29 De Vere Gardens, Kensington"},
  {"placename_id":30133,"placename":"22 Cleveland St., Fitzrovia"},
  {"placename_id":30134,"placename":"141-16 Bayham St., Camden Town"},
  {"placename_id":30136,"placename":"70 Margaret St., Fitzrovia"},
  {"placename_id":30137,"placename":"30 Hungerford Stairs"},
  {"placename_id":30140,"placename":"18 Bentinck St., Marylebone"},
  {"placename_id":30141,"placename":"18 Selwood Place, South Kensington"},
  {"placename_id":30142,"placename":"St. Luke's church, Chelsea"},
  {"placename_id":30144,"placename":"Furnival's Inn"},
  {"placename_id":30145,"placename":"1 Devonshire Terrace in Marylebone Road"},
  {"placename_id":30146,"placename":"1 Chester Row in Belgravia"},
  {"placename_id":30147,"placename":"Tavistock Square"},
  {"placename_id":30148,"placename":"3 Hanover Square"},
  {"placename_id":30149,"placename":"16 Somers Place, S.W.2"},
  {"placename_id":30150,"placename":"Southwick Place"},
  {"placename_id":30151,"placename":"Hyde Park"},
  {"placename_id":30152,"placename":"16 Wellington St. in Covent Garden"},
  {"placename_id":30153,"placename":"11 Wellington Street"},
  {"placename_id":30154,"placename":"Lincoln's Inn Fields"},
  {"placename_id":30155,"placename":"6 Keppel Street"},
  {"placename_id":30156,"placename":"39 Montagu Square in Marylebone"},
  {"placename_id":30157,"placename":"Wellbeck St, Marylebone"},
  {"placename_id":30158,"placename":"142 The Strand"},
  {"placename_id":30159,"placename":"21 Cambridge St, Pimlico"},
  {"placename_id":30160,"placename":"10 Harewood Square"},
  {"placename_id":30161,"placename":"16 Blandford Square in Marylebone"},
  {"placename_id":30162,"placename":"21 North Bank"},
  {"placename_id":30163,"placename":"Cheyne Walk"},
  {"placename_id":30164,"placename":"Highgate Cemetry"},
  {"placename_id":30165,"placename":"13 Salisbury Street"},
  {"placename_id":30167,"placename":"9 Charles St."},
  {"placename_id":30168,"placename":"St. James's Church, Sussex Gardens"},
  {"placename_id":30169,"placename":"16 Tite St."},
  {"placename_id":30170,"placename":"10-11 St. James's Place"},
  {"placename_id":30171,"placename":"St. James's Theater, St. James's"},
  {"placename_id":30172,"placename":"13 Victoria Grove"},
  {"placename_id":30173,"placename":"37 Fitzroy St."},
  {"placename_id":30174,"placename":"36 Osnaburgh Street"},
  {"placename_id":30175,"placename":"29 Fitzroy Square"},
  {"placename_id":30176,"placename":"10 Adelphi Terrace"},
  {"placename_id":30178,"placename":"43 Villiers Street"},
  {"placename_id":30179,"placename":"All Soul's Church, Langham Place"},
  {"placename_id":30180,"placename":"Brown's Hotel on Dover St."},
  {"placename_id":30181,"placename":"84 Ebury St., Pimlico"},
  {"placename_id":30182,"placename":"Middlesex hospital"},
  {"placename_id":30184,"placename":"14 Edith Road in Kensington"},
  {"placename_id":30185,"placename":"8 Woodstock Rd. in Bedford Park, Chiswick"},
  {"placename_id":30186,"placename":"3 Blenheim Rd., Bedford Park"},
  {"placename_id":30187,"placename":"the British Museum"},
  {"placename_id":30188,"placename":"58 Eardley Crescent, South Kensington"},
  {"placename_id":30189,"placename":"6 Berkeley Rd., Chalk Farm"},
  {"placename_id":30190,"placename":"Woburn Walk"},
  {"placename_id":30191,"placename":"17 Lancaster Gardens in Bayswater"},
  {"placename_id":30193,"placename":"Bloomsbury"},
  {"placename_id":30194,"placename":"46 Gordon Square"},
  {"placename_id":30195,"placename":"29, Fitzroy Square"},
  {"placename_id":30196,"placename":"Brunswick Square"},
  {"placename_id":30197,"placename":"the Strand"},
  {"placename_id":30200,"placename":"Hotel Belgravia"},
  {"placename_id":30201,"placename":"28b Campden Grove"},
  {"placename_id":30202,"placename":"St. Paul's Church, Portman Square"},
  {"placename_id":30203,"placename":"17a Canonbury Square"},
  {"placename_id":30204,"placename":"the Ritz"},
  {"placename_id":30205,"placename":"St. James Stree"},
  {"placename_id":30206,"placename":"Hyde Park Hotel"},
  {"placename_id":30207,"placename":"Mecklenburgh Square, Bloomsbury"},
  {"placename_id":30208,"placename":"19 Gower Mews, Fitzrovia"},
  {"placename_id":30209,"placename":"Gordon Square, Bloomsbury"},
  {"placename_id":30210,"placename":"5 St. James St., St James's"},
  {"placename_id":30211,"placename":"Albany Court, Piccadilly"},
  {"placename_id":30212,"placename":"the Wheatsheaf"},
  {"placename_id":30213,"placename":"The French House"},
  {"placename_id":30214,"placename":"5 Redcliffe St., Earlscourt"},
  {"placename_id":30215,"placename":"Manresa Road, Chelsea"},
  {"placename_id":30216,"placename":"Cross Keys on Lawrence Street"},
  {"placename_id":30217,"placename":"108 Maida Vale"},
  {"placename_id":30219,"placename":"Primrose Hill"},
  {"placename_id":30220,"placename":"Queen's Head pub"},
  {"placename_id":30221,"placename":"194 Regent's Park Rd."},
  {"placename_id":30222,"placename":"22 Portobello Rd., Notting Hill"},
  {"placename_id":30223,"placename":"East End"},
  {"placename_id":30224,"placename":"Pond Street and South End Road in Hampstead"},
  {"placename_id":30225,"placename":"77 Parliament Hill"},
  {"placename_id":30226,"placename":"10a Mortimer Crescent in Maida Vale"},
  {"placename_id":30228,"placename":"Senate House of London University"},
  {"placename_id":30229,"placename":"Marquis of Granby in Fitzrovia"},
  {"placename_id":30230,"placename":"Robert Street"},
  {"placename_id":30231,"placename":"Admiral's Walk, Hampstead"},
  {"placename_id":30232,"placename":"21 Buckingham Street"},
  {"placename_id":30233,"placename":"25 Bridge St., Westminster"},
  {"placename_id":30234,"placename":"10 King St., Covent Garden"},
  {"placename_id":30235,"placename":"7 S. Barnard's Inn"},
  {"placename_id":30236,"placename":"55 Frith St., Soho"},
  {"placename_id":30237,"placename":"Hudson's Hotel, Covent Garden"},
  {"placename_id":30238,"placename":"7 Portland Place"},
  {"placename_id":30240,"placename":"71 Berners St., Soho"},
  {"placename_id":30241,"placename":"42 Norfolk St."},
  {"placename_id":30242,"placename":"South Grove, Highgate"},
  {"placename_id":30243,"placename":"3, The Grove"},
  {"placename_id":30244,"placename":"St. Michael's"},
  {"placename_id":30245,"placename":"41 Skinner St., London"},
  {"placename_id":30246,"placename":"56 Margaret St., Cavendish Square"},
  {"placename_id":30247,"placename":"5 Church Terrace, St. Pancras"},
  {"placename_id":30248,"placename":"Nelson Square, Blackfriars Rd."},
  {"placename_id":30249,"placename":"1 Hans Place"},
  {"placename_id":30250,"placename":"Marchmont St., Bloomsbury"},
  {"placename_id":30251,"placename":"13 Norfolk St."},
  {"placename_id":30252,"placename":"18 Norfolk St."},
  {"placename_id":30253,"placename":"19 Mabledon Place, Euston Rd."},
  {"placename_id":30254,"placename":"119 Great Russell St."},
  {"placename_id":30255,"placename":"14 Speldhurst St., Bruswick Square"},
  {"placename_id":30256,"placename":"5 Bartholomew Place, Kentish Town"},
  {"placename_id":30257,"placename":"51 George St., Portman Square"},
  {"placename_id":30258,"placename":"4 Oxford Terrace"},
  {"placename_id":30259,"placename":"7 Upper Eaton St"},
  {"placename_id":30260,"placename":"36 North Bank, Regent's Park"},
  {"placename_id":30261,"placename":"24 South Audley St"},
  {"placename_id":30262,"placename":"41d Park St., Grosvenor Square"},
  {"placename_id":30263,"placename":"34 Half Moon St."},
  {"placename_id":30264,"placename":"11 Portugal St., Holborn"},
  {"placename_id":30265,"placename":"Lower Richmond Rd., Putney"},
  {"placename_id":30266,"placename":"24 Chester Square, Belgravia"},
  {"placename_id":30267,"placename":"9 Selwood Terrace, South Kensington"},
  {"placename_id":30268,"placename":"Vale of Health, Hampstead"},
  {"placename_id":30270,"placename":"13b Earl's Court Square, Earlscourt"},
  {"placename_id":30271,"placename":"110 Heath St., Hampstead"},
  {"placename_id":30272,"placename":"Garland's Hotel, St. James's"},
  {"placename_id":30274,"placename":"17 North Road in Highgate"},
  {"placename_id":30275,"placename":"82 Talbot Road, Bayswater"},
  {"placename_id":30276,"placename":"101 Mount St., Mayfair"},
  {"placename_id":30277,"placename":"Eaton Place"},
  {"placename_id":30278,"placename":"Lower Belgrave St."},
  {"placename_id":30279,"placename":"2 Chester Square"},
  {"placename_id":30280,"placename":"7 Chester Street, Belgravia"},
  {"placename_id":30282,"placename":"16 Grafton St."},
  {"placename_id":30283,"placename":"124 Mount St. Mayfair"},
  {"placename_id":30284,"placename":"18 Grosvenor Place in Belgravia"},
  {"placename_id":30286,"placename":"22 Dorset St."},
  {"placename_id":30287,"placename":"St. John's Wood"},
  {"placename_id":30288,"placename":"3 Great James St., Holborn"},
  {"placename_id":30289,"placename":"25 Guilford St."},
  {"placename_id":30290,"placename":"23, Tedworth Square"},
  {"placename_id":30291,"placename":"Langham Place, Marylebone"},
  {"placename_id":30292,"placename":"34 DeVere Gardens in Kensington"},
  {"placename_id":30293,"placename":"3 Bolton Street"},
  {"placename_id":30294,"placename":"Kensington Gardens"},
  {"placename_id":30295,"placename":"Reform Club"},
  {"placename_id":30296,"placename":"Chelsea Old Church"},
  {"placename_id":30297,"placename":"Manresa Road"},
  {"placename_id":30298,"placename":"Bury Str"},
  {"placename_id":30299,"placename":"18 Crawford Mansions"},
  {"placename_id":30300,"placename":"9 Clarence Mansions"},
  {"placename_id":30301,"placename":"5 Chester Row"},
  {"placename_id":30302,"placename":"Russell Square"},
  {"placename_id":30303,"placename":"33 Courtfield Road in Kensington"},
  {"placename_id":30304,"placename":"9 Grenville Place"},
  {"placename_id":30305,"placename":"Carlyle Mansions"},
  {"placename_id":30306,"placename":"St. Barnabas's Church, Kensington"},
  {"placename_id":30307,"placename":"Kensington Court Gardens"},
  {"placename_id":30308,"placename":"the Round Pond"},
  {"placename_id":30309,"placename":"Islington"},
  {"placename_id":30310,"placename":"8 Duchess St., Marylebone"},
  {"placename_id":30311,"placename":"48 Langham St., Marylebone"},
  {"placename_id":30312,"placename":"10 Rowan Rd., Brook Green"},
  {"placename_id":30314,"placename":"St. Mary Abbots"},
  {"placename_id":30315,"placename":"2a Granville Place"},
  {"placename_id":30316,"placename":"39 Addison Rd, West Kensington"},
  {"placename_id":30317,"placename":"5 Holland Place Chambers"},
  {"placename_id":30318,"placename":"Kensington Church Street"},
  {"placename_id":30320,"placename":"British Museum"},
  {"placename_id":30321,"placename":"8 Duchess St."},
  {"placename_id":30322,"placename":"Kensington Church Walk"},
  {"placename_id":30323,"placename":"7 Christchurch Place"},
  {"placename_id":30324,"placename":"44 Mecklenburgh Square"},
  {"placename_id":30325,"placename":"Sloane St."},
  {"placename_id":30326,"placename":"32 Wellington Square"},
  {"placename_id":30327,"placename":"75 Ebury Street, Belgravia"},
  {"placename_id":30328,"placename":"26 Hanover Square, St. James's"},
  {"placename_id":30329,"placename":"St. George the Martyr's church"},
  {"placename_id":30330,"placename":"3 Chalcot Square"},
  {"placename_id":30331,"placename":"Regent's Park Zoo"},
  {"placename_id":30332,"placename":"23 Fitzroy Road"},
  {"placename_id":31001,"placename":"Paddington Station"},
  {"placename_id":31002,"placename":"London Bridge"},
  {"placename_id":31003,"placename":"London's column"},
  {"placename_id":31004,"placename":"Willowbed Road"},
  {"placename_id":31005,"placename":"Acton"},
  {"placename_id":31006,"placename":"Paddington district"},
  {"placename_id":31007,"placename":"Doughty Street"},
  {"placename_id":31009,"placename":"Earl's Court"},
  {"placename_id":31010,"placename":"Billingsgate"},
  {"placename_id":31011,"placename":"Eastcheap"},
  {"placename_id":31012,"placename":"the Embankment"},
  {"placename_id":31013,"placename":"Hampstead"},
  {"placename_id":31015,"placename":"West Kensington"},
  {"placename_id":31016,"placename":"Regent's Park district"},
  {"placename_id":31017,"placename":"Camden Town"},
  {"placename_id":31018,"placename":"Tottenham Court Road"},
  {"placename_id":31019,"placename":"Oxford Street"},
  {"placename_id":31020,"placename":"Covent Garden"},
  {"placename_id":31022,"placename":"Waterloo Bridge"},
  {"placename_id":31023,"placename":"Lambeth"},
  {"placename_id":31025,"placename":"Hungerford Bridge"},
  {"placename_id":31026,"placename":"Embankment"},
  {"placename_id":31027,"placename":"Westminster"},
  {"placename_id":31028,"placename":"Trafalgar"},
  {"placename_id":31029,"placename":"Charing Cross Road"},
  {"placename_id":31031,"placename":"Palace Theatre"},
  {"placename_id":31032,"placename":"Regent's Park"},
  {"placename_id":31033,"placename":"Mayfair"},
  {"placename_id":31034,"placename":"Luton Road"},
  {"placename_id":31035,"placename":"Slough"},
  {"placename_id":31037,"placename":"Farnham Common, Burnham Beeches"},
  {"placename_id":31039,"placename":"Crickham-on-Thames"},
  {"placename_id":31041,"placename":"Regent Street"},
  {"placename_id":31042,"placename":"Piccadilly Circus"},
  {"placename_id":31043,"placename":"Brewer's Yard"},
  {"placename_id":31044,"placename":"Lambeth Cut"},
  {"placename_id":31045,"placename":"Waterloo Road"},
  {"placename_id":31046,"placename":"Westminster Bridge Road"},
  {"placename_id":31047,"placename":"Edgware Road"},
  {"placename_id":31050,"placename":"the little church of St John"},
  {"placename_id":31051,"placename":"Greenwich Park"},
  {"placename_id":31052,"placename":"Greenwich Observatory"},
  {"placename_id":31053,"placename":"Greenwich Hospital"},
  {"placename_id":31054,"placename":"Naval College"},
  {"placename_id":31055,"placename":"Queen's House"},
  {"placename_id":31056,"placename":"Canonbury Square"},
  {"placename_id":31059,"placename":"King William Street"},
  {"placename_id":31060,"placename":"Saint Mary Woolnoth"},
  {"placename_id":31061,"placename":"Sweet Thames"},
  {"placename_id":31062,"placename":"Cannon Street Hotel"},
  {"placename_id":31065,"placename":"Magnus Martyr"},
  {"placename_id":31067,"placename":"Greenwich reach"},
  {"placename_id":31068,"placename":"Isle of Dogs"},
  {"placename_id":31069,"placename":"Highbury"},
  {"placename_id":31070,"placename":"Richmond"},
  {"placename_id":31071,"placename":"Kew"},
  {"placename_id":31072,"placename":"Moorgate"},
  {"placename_id":31073,"placename":"Three Mile Cross"},
  {"placename_id":31075,"placename":"Vere Street"},
  {"placename_id":31077,"placename":"Whitechapel"},
  {"placename_id":31079,"placename":"Maida Vale"},
  {"placename_id":31080,"placename":"Marylebone Church"},
  {"placename_id":31081,"placename":"Welbeck Street"},
  {"placename_id":31082,"placename":"Farnham"},
  {"placename_id":31084,"placename":"Trafalgar Square"},
  {"placename_id":31085,"placename":"Waterloo"},
  {"placename_id":31086,"placename":"Victoria"},
  {"placename_id":31087,"placename":"Soho"},
  {"placename_id":31088,"placename":"Lord's"},
  {"placename_id":31091,"placename":"Canada House"},
  {"placename_id":31092,"placename":"Crooms Hill"},
  {"placename_id":31093,"placename":"London streets"},
  {"placename_id":31094,"placename":"Baker Street"},
  {"placename_id":31095,"placename":"New Kent Road"},
  {"placename_id":31097,"placename":"Wallington"},
  {"placename_id":31098,"placename":"Portman Square"},
  {"placename_id":31099,"placename":"East India docks"},
  {"placename_id":31101,"placename":"central London"},
  {"placename_id":31103,"placename":"Old Kent Road"},
  {"placename_id":31105,"placename":"Bank of England"},
  {"placename_id":31106,"placename":"Cheapside"},
  {"placename_id":31107,"placename":"Holborn"},
  {"placename_id":31108,"placename":"Marylebone"},
  {"placename_id":31109,"placename":"Madame Tussauds"},
  {"placename_id":31110,"placename":"Westminster Bridge"},
  {"placename_id":31111,"placename":"Woolwich"},
  {"placename_id":31112,"placename":"Criterion"},
  {"placename_id":31113,"placename":"the public shelter"},
  {"placename_id":31115,"placename":"the silver Flood"},
  {"placename_id":31116,"placename":"Tyburn"},
  {"placename_id":31117,"placename":"the Elephant"},
  {"placename_id":31119,"placename":"Lansdowne Terrace"},
  {"placename_id":31121,"placename":"Piccadilly"},
  {"placename_id":31122,"placename":"Tube stations"},
  {"placename_id":31123,"placename":"the Savoy"},
  {"placename_id":31124,"placename":"Dorset Square"},
  {"placename_id":31125,"placename":"Oxford Circus"},
  {"placename_id":31126,"placename":"Marble Arch"},
  {"placename_id":31129,"placename":"Chancery Lane"},
  {"placename_id":31130,"placename":"St. Paul's"},
  {"placename_id":31131,"placename":"the Inner Circle"},
  {"placename_id":31132,"placename":"St. Alfege"},
  {"placename_id":31134,"placename":"the docks"},
  {"placename_id":31135,"placename":"GRUBSTREET"},
  {"placename_id":31136,"placename":"Moorfields"},
  {"placename_id":31137,"placename":"the Slade"},
  {"placename_id":31139,"placename":"Victoria Station"},
  {"placename_id":31140,"placename":"Liverpool Street Station"},
  {"placename_id":31141,"placename":"Blackfriar's Bridge"},
  {"placename_id":31142,"placename":"Leicester Square"},
  {"placename_id":31144,"placename":"Green Park"},
  {"placename_id":31145,"placename":"Blackfriars Bridge"},
  {"placename_id":31146,"placename":"Curzon Street"},
  {"placename_id":31147,"placename":"the Albany"},
  {"placename_id":31148,"placename":"the park"},
  {"placename_id":31150,"placename":"Burlington Street"},
  {"placename_id":31151,"placename":"Berkeley Square"},
  {"placename_id":31152,"placename":"Willis's Rooms"},
  {"placename_id":31153,"placename":"Wardour Street"},
  {"placename_id":31154,"placename":"Euston Road"},
  {"placename_id":31155,"placename":"Achilles Statue"},
  {"placename_id":31156,"placename":"Cursitor Street"},
  {"placename_id":31158,"placename":"Charing Cross"},
  {"placename_id":31159,"placename":"Pall Mall"},
  {"placename_id":31160,"placename":"Old Slaughters'"},
  {"placename_id":31162,"placename":"St. Martin's Lane"},
  {"placename_id":31163,"placename":"Bond Street"},
  {"placename_id":31164,"placename":"Leadenhall Street"},
  {"placename_id":31165,"placename":"Castle Street Mews"},
  {"placename_id":31166,"placename":"Rupert Street"},
  {"placename_id":31167,"placename":"Hoxton Road"},
  {"placename_id":31168,"placename":"Grosvenor Square"},
  {"placename_id":31169,"placename":"Blue Gate Fields"},
  {"placename_id":31171,"placename":"the Churchill"},
  {"placename_id":31172,"placename":"South Audley Street"},
  {"placename_id":31173,"placename":"Chiswick Mall"},
  {"placename_id":31174,"placename":"St Nicholas Church"},
  {"placename_id":31175,"placename":"Newman Street"},
  {"placename_id":31176,"placename":"Gerrard Street"},
  {"placename_id":31177,"placename":"Artists' quarter"},
  {"placename_id":31178,"placename":"Kensington turnpike"},
  {"placename_id":31179,"placename":"Southampton Row"},
  {"placename_id":31180,"placename":"Covent Garden Market"},
  {"placename_id":31181,"placename":"Thames Street"},
  {"placename_id":31182,"placename":"Vauxhall"},
  {"placename_id":31183,"placename":"Royal Gardens"},
  {"placename_id":31184,"placename":"Hanover Square"},
  {"placename_id":31185,"placename":"Lambeth Palace"},
  {"placename_id":31186,"placename":"Swallow Street"},
  {"placename_id":31187,"placename":"Great Gaunt Street"},
  {"placename_id":31188,"placename":"Park Lane"},
  {"placename_id":31189,"placename":"St. James's Street"},
  {"placename_id":31190,"placename":"Exeter-street"},
  {"placename_id":31191,"placename":"the Pine Apple in New-street"},
  {"placename_id":31195,"placename":"St. James's-square"},
  {"placename_id":31196,"placename":"Warwick-lane"},
  {"placename_id":31197,"placename":"Drury-lane theatre"},
  {"placename_id":31198,"placename":"the riding Thames"},
  {"placename_id":31199,"placename":"Playgoers' Club"},
  {"placename_id":31200,"placename":"the Adelphi"},
  {"placename_id":31201,"placename":"Whitehall lane"},
  {"placename_id":31202,"placename":"Stoke Newington"},
  {"placename_id":31203,"placename":"house of commons"},
  {"placename_id":31206,"placename":"Coventry House, South Place"},
  {"placename_id":31211,"placename":"Fleet St."},
  {"placename_id":31212,"placename":"Ealing"},
  {"placename_id":31214,"placename":"Vauxhall Gardens"},
  {"placename_id":31215,"placename":"Fulham Road"},
  {"placename_id":31217,"placename":"the Ring"},
  {"placename_id":31218,"placename":"the Silver Thames"},
  {"placename_id":31219,"placename":"Structure of Majestick Frame"},
  {"placename_id":31220,"placename":"Hampton-Court"},
  {"placename_id":31221,"placename":"the Mall"},
  {"placename_id":31222,"placename":"St James's Park"},
  {"placename_id":31223,"placename":"the charter'd Thames"},
  {"placename_id":31224,"placename":"Grub Street"},
  {"placename_id":31225,"placename":"the Tower"},
  {"placename_id":31226,"placename":"10 Keats Grove"},
  {"placename_id":31228,"placename":"Jermyn Street"},
  {"placename_id":31229,"placename":"Claridge's"},
  {"placename_id":31230,"placename":"W.1."},
  {"placename_id":31231,"placename":"King's Cross"},
  {"placename_id":31234,"placename":"St. James's Arcade"},
  {"placename_id":31237,"placename":"Old Compton Street"},
  {"placename_id":31238,"placename":"High Street"},
  {"placename_id":31241,"placename":"The Exchange"},
  {"placename_id":31243,"placename":"Drury Lane Theatre"},
  {"placename_id":31244,"placename":"Covent Garden Theatre"},
  {"placename_id":31245,"placename":"Ivy Lane"},
  {"placename_id":31246,"placename":"Paternoster Row"},
  {"placename_id":31247,"placename":"Grosvenor-Square"},
  {"placename_id":31249,"placename":"Chelsea Hospital"},
  {"placename_id":31250,"placename":"Fulham"},
  {"placename_id":31253,"placename":"St. Paul's Church"},
  {"placename_id":31255,"placename":"Bedlam"},
  {"placename_id":31256,"placename":"The Court of Common Pleas"},
  {"placename_id":31257,"placename":"Queen's Bench"},
  {"placename_id":31258,"placename":"the Abbey"},
  {"placename_id":31259,"placename":"King Street"},
  {"placename_id":31260,"placename":"Great Windmill Street"},
  {"placename_id":31262,"placename":"Ropewalk"},
  {"placename_id":31263,"placename":"Davies Street"},
  {"placename_id":31264,"placename":"King's Road"},
  {"placename_id":31265,"placename":"Reform"},
  {"placename_id":31266,"placename":"Travellers"},
  {"placename_id":31267,"placename":"St. James's Palace"},
  {"placename_id":31268,"placename":"St. James's Park"},
  {"placename_id":31269,"placename":"Bentinck House"},
  {"placename_id":31270,"placename":"Blackfriars"},
  {"placename_id":31271,"placename":"Cleopatra's Needle"},
  {"placename_id":31272,"placename":"Belgrave Square"},
  {"placename_id":31274,"placename":"Wood Street"},
  {"placename_id":31275,"placename":"the Tabard"},
  {"placename_id":31276,"placename":"Southwerk"},
  {"placename_id":31277,"placename":"Talbot Yard"},
  {"placename_id":31278,"placename":"Panton Street"},
  {"placename_id":31279,"placename":"Brompton Road"},
  {"placename_id":31280,"placename":"St. George's"},
  {"placename_id":31281,"placename":"St. James's"},
  {"placename_id":31282,"placename":"Newington Butts"},
  {"placename_id":31283,"placename":"Heathrow"},
  {"placename_id":31284,"placename":"Walton"},
  {"placename_id":31285,"placename":"Wilton"},
  {"placename_id":31286,"placename":"Guilford Street"},
  {"placename_id":31287,"placename":"5 Park Crescent"},
  {"placename_id":31288,"placename":"Campden Hill"},
  {"placename_id":31291,"placename":"Clapham"},
  {"placename_id":31292,"placename":"St John's Wood"},
  {"placename_id":31293,"placename":"Kensington"},
  {"placename_id":31294,"placename":"Gray's Inn"},
  {"placename_id":31295,"placename":"Stockwell"},
  {"placename_id":31296,"placename":"Grosvenor Place"},
  {"placename_id":31297,"placename":"Mellows"},
  {"placename_id":31298,"placename":"Portman Street"},
  {"placename_id":31299,"placename":"Queen's Gate"},
  {"placename_id":31300,"placename":"the City"},
  {"placename_id":31301,"placename":"Ludgate Hill"},
  {"placename_id":31303,"placename":"the Temple"},
  {"placename_id":31305,"placename":"Soane Museum"},
  {"placename_id":31306,"placename":"Royal Opera House"},
  {"placename_id":31307,"placename":"Notting Hill"},
  {"placename_id":31308,"placename":"Sutton"},
  {"placename_id":31309,"placename":"Wimbledon"},
  {"placename_id":31310,"placename":"Buckingham Gate"},
  {"placename_id":31311,"placename":"Upper Baker Street"},
  {"placename_id":31313,"placename":"Knightsbridge"},
  {"placename_id":31314,"placename":"Sloane Street"},
  {"placename_id":31316,"placename":"Battersea"},
  {"placename_id":31317,"placename":"Poplar High Street"},
  {"placename_id":31318,"placename":"Chelsea Bridge"},
  {"placename_id":31319,"placename":"Northumberland Avenue"},
  {"placename_id":31320,"placename":"St Paul's"},
  {"placename_id":31321,"placename":"Gower Street"},
  {"placename_id":31322,"placename":"Prince Consort Mansions, Battersea"},
  {"placename_id":31323,"placename":"Oakley Street"},
  {"placename_id":31324,"placename":"Albert Bridge"},
  {"placename_id":31325,"placename":"Sloane Square"},
  {"placename_id":31326,"placename":"Bayswater Road"},
  {"placename_id":31327,"placename":"Paddington"},
  {"placename_id":31329,"placename":"Quebec Street"},
  {"placename_id":31330,"placename":"eastern slums"},
  {"placename_id":31331,"placename":"Tower Hill"},
  {"placename_id":31335,"placename":"Pennyfields"},
  {"placename_id":31336,"placename":"Wapping"},
  {"placename_id":31337,"placename":"Limehouse"},
  {"placename_id":31338,"placename":"East India Dock Road"},
  {"placename_id":31339,"placename":"Middlesex Street"},
  {"placename_id":31340,"placename":"Bow"},
  {"placename_id":31341,"placename":"Romton"},
  {"placename_id":31342,"placename":"Edbury"},
  {"placename_id":31343,"placename":"Ilford"},
  {"placename_id":31344,"placename":"King's Cross Station"},
  {"placename_id":31345,"placename":"Charing Cross Bridge"},
  {"placename_id":31346,"placename":"Cromley"},
  {"placename_id":31347,"placename":"Lower Binfield"},
  {"placename_id":31348,"placename":"Ide Hill"},
  {"placename_id":31349,"placename":"Wandsworth"},
  {"placename_id":31350,"placename":"Westminster-Abbey"},
  {"placename_id":31351,"placename":"Doctors Commons"},
  {"placename_id":31352,"placename":"Newgate"},
  {"placename_id":31353,"placename":"Marybone-Gardens"},
  {"placename_id":31354,"placename":"the Poultry"},
  {"placename_id":31355,"placename":"Essex-street"},
  {"placename_id":31356,"placename":"Strand"},
  {"placename_id":31357,"placename":"Ivy-lane"},
  {"placename_id":31358,"placename":"St. Luke's Hospital"},
  {"placename_id":31360,"placename":"Old Bailey"},
  {"placename_id":31362,"placename":"the Mitre"},
  {"placename_id":31363,"placename":"Fleet Street"},
  {"placename_id":31364,"placename":"Spring-garden"},
  {"placename_id":31365,"placename":"Saint George's-Fields"},
  {"placename_id":31366,"placename":"Lincoln's-Inn"},
  {"placename_id":31367,"placename":"Hummums"},
  {"placename_id":31368,"placename":"Hedge-lane"},
  {"placename_id":31369,"placename":"St. James's-street"},
  {"placename_id":31370,"placename":"St. James's-place"},
  {"placename_id":31371,"placename":"Westminster-Hall"},
  {"placename_id":31372,"placename":"Butcher-row"},
  {"placename_id":31373,"placename":"Bolt-court"},
  {"placename_id":31374,"placename":"St. Clement's church"},
  {"placename_id":31375,"placename":"Fleet-street"},
  {"placename_id":31376,"placename":"Royal Exchange"},
  {"placename_id":31377,"placename":"Blenheim park"},
  {"placename_id":31378,"placename":"Chapel-house"},
  {"placename_id":31379,"placename":"Gough-square, Fleet-street"},
  {"placename_id":31380,"placename":"Covent-Garden"},
  {"placename_id":31381,"placename":"Grub-street"},
  {"placename_id":31382,"placename":"Blackfriars-bridge"},
  {"placename_id":31385,"placename":"Temple-bar"},
  {"placename_id":31386,"placename":"Cock-lane"},
  {"placename_id":31387,"placename":"Johnson's-court, No. 7"},
  {"placename_id":31388,"placename":"Boltcourt"},
  {"placename_id":31390,"placename":"Black-friars"},
  {"placename_id":31393,"placename":"Stanhope Gate"},
  {"placename_id":31394,"placename":"Bayswater"},
  {"placename_id":31395,"placename":"Montpellier Square"},
  {"placename_id":31396,"placename":"Highgate"},
  {"placename_id":31397,"placename":"Stanhope Place"},
  {"placename_id":31398,"placename":"Hyde Park Mansions"},
  {"placename_id":31399,"placename":"Prince's Gardens"},
  {"placename_id":31400,"placename":"Ladbroke Grove"},
  {"placename_id":31401,"placename":"Praed Street Station"},
  {"placename_id":31402,"placename":"Praed Street"},
  {"placename_id":31403,"placename":"Notting Hill Gate"},
  {"placename_id":31404,"placename":"South Kensington"},
  {"placename_id":31405,"placename":"Wistaria Avenue"},
  {"placename_id":31406,"placename":"the river Thames"},
  {"placename_id":31408,"placename":"Pangbourne"},
  {"placename_id":31409,"placename":"Robin Hill"},
  {"placename_id":31410,"placename":"No. 62, Montpellier Square"},
  {"placename_id":31411,"placename":"Knightsbridge Gate"},
  {"placename_id":31412,"placename":"the Row"},
  {"placename_id":31413,"placename":"Albert Gate"},
  {"placename_id":31414,"placename":"Highgate Cemetery"},
  {"placename_id":31415,"placename":"Ironmonger Lane"},
  {"placename_id":31416,"placename":"Green Street"},
  {"placename_id":31418,"placename":"Richmond Park"},
  {"placename_id":31419,"placename":"Sheen Gate"},
  {"placename_id":31420,"placename":"the Haversnake"},
  {"placename_id":31422,"placename":"the Botanical Garden"},
  {"placename_id":31423,"placename":"Sloane Square station"},
  {"placename_id":31424,"placename":"the Angel"},
  {"placename_id":31425,"placename":"St. John's Road"},
  {"placename_id":31426,"placename":"Sadler's Wells Theatre"},
  {"placename_id":31427,"placename":"Exmouth Street"},
  {"placename_id":31428,"placename":"Coppice Row"},
  {"placename_id":31429,"placename":"Hockley-in-the-Hole"},
  {"placename_id":31431,"placename":"Saffron Hill"},
  {"placename_id":31432,"placename":"Field Lane"},
  {"placename_id":31433,"placename":"Pentonville"},
  {"placename_id":31434,"placename":"Saint John's Road"},
  {"placename_id":31435,"placename":"Gray's Inn Lane"},
  {"placename_id":31436,"placename":"Smithfield"},
  {"placename_id":31437,"placename":"Highgate Hill"},
  {"placename_id":31438,"placename":"Caen Wood"},
  {"placename_id":31439,"placename":"Hampstead Heath"},
  {"placename_id":31440,"placename":"Vale of Heath"},
  {"placename_id":31441,"placename":"Hendon"},
  {"placename_id":31442,"placename":"Rotherhithe"},
  {"placename_id":31443,"placename":"Jacob's Island"},
  {"placename_id":31444,"placename":"Folly Ditch"},
  {"placename_id":31445,"placename":"Mill Lane"},
  {"placename_id":31447,"placename":"Mount Street"},
  {"placename_id":31448,"placename":"Broadcasting House"},
  {"placename_id":31449,"placename":"St John's Wood Road"},
  {"placename_id":31451,"placename":"St James's Square"},
  {"placename_id":31452,"placename":"B.B.C."},
  {"placename_id":31453,"placename":"Regent's Canal"},
  {"placename_id":31454,"placename":"the Angel station"},
  {"placename_id":31456,"placename":"Queen Alexandra Hall"},
  {"placename_id":31457,"placename":"Charlotte Street"},
  {"placename_id":31458,"placename":"Hyde Park Corner"},
  {"placename_id":31459,"placename":"Alexandra Hall"},
  {"placename_id":31460,"placename":"Grosvenor Gardens"},
  {"placename_id":31462,"placename":"Number 3, Little King William's-alley"},
  {"placename_id":31463,"placename":"No. 25, in Gordon-place"},
  {"placename_id":31464,"placename":"George's-yard"},
  {"placename_id":31465,"placename":"Eaton-square"},
  {"placename_id":31466,"placename":"Covent-garden market"},
  {"placename_id":31467,"placename":"Marsh-gate"},
  {"placename_id":31468,"placename":"Victoria Theatre"},
  {"placename_id":31469,"placename":"Victoria gallery"},
  {"placename_id":31470,"placename":"St. Paul's Churchyard"},
  {"placename_id":31471,"placename":"Scotland-yard"},
  {"placename_id":31472,"placename":"Northumberland House"},
  {"placename_id":31473,"placename":"Northumberland-street"},
  {"placename_id":31474,"placename":"Whitehall-place"},
  {"placename_id":31475,"placename":"Patent Shot Manufactory"},
  {"placename_id":31476,"placename":"Waterloo-bridge"},
  {"placename_id":31477,"placename":"London-bridge"},
  {"placename_id":31478,"placename":"Hungerford"},
  {"placename_id":31479,"placename":"Seven Dials"},
  {"placename_id":31480,"placename":"the Dials"},
  {"placename_id":31481,"placename":"Monmouth-street"},
  {"placename_id":31482,"placename":"Hammersmith suspension-bridge"},
  {"placename_id":31483,"placename":"Holywell-street"},
  {"placename_id":31484,"placename":"Dials"},
  {"placename_id":31485,"placename":"Fitzroy-square"},
  {"placename_id":31486,"placename":"Tottenham-court-road"},
  {"placename_id":31488,"placename":"Lloyd's"},
  {"placename_id":31489,"placename":"Hackney"},
  {"placename_id":31490,"placename":"Clapton"},
  {"placename_id":31491,"placename":"Stamford-hill"},
  {"placename_id":31492,"placename":"Almack's"},
  {"placename_id":31493,"placename":"Hampstead-road"},
  {"placename_id":31494,"placename":"Kilburn-road"},
  {"placename_id":31495,"placename":"Gravesend"},
  {"placename_id":31496,"placename":"Penitentiary"},
  {"placename_id":31499,"placename":"Westminster-bridge"},
  {"placename_id":31501,"placename":"Astley's"},
  {"placename_id":31502,"placename":"Greenwich Fair"},
  {"placename_id":31503,"placename":"the Observatory"},
  {"placename_id":31505,"placename":"Gray's-inn-lane"},
  {"placename_id":31506,"placename":"Catherine-street"},
  {"placename_id":31507,"placename":"Sadler's Wells"},
  {"placename_id":31508,"placename":"Surrey"},
  {"placename_id":31509,"placename":"Vauxhall-Gardens"},
  {"placename_id":31510,"placename":"Oxford-street"},
  {"placename_id":31511,"placename":"Waterloo-place"},
  {"placename_id":31512,"placename":"Golden Cross"},
  {"placename_id":31514,"placename":"Chancery"},
  {"placename_id":31515,"placename":"Lincoln's Inn Hall"},
  {"placename_id":31516,"placename":"Holborn Hill"},
  {"placename_id":31517,"placename":"Temple Bar"},
  {"placename_id":31518,"placename":"Shooter's Hill"},
  {"placename_id":31520,"placename":"London Town"},
  {"placename_id":31521,"placename":"Bow Street"},
  {"placename_id":31523,"placename":"Kennington"},
  {"placename_id":31524,"placename":"Mount Pleasant"},
  {"placename_id":31526,"placename":"The Bench"},
  {"placename_id":31527,"placename":"Mansion House"},
  {"placename_id":31529,"placename":"Chepe"},
  {"placename_id":31530,"placename":"Poules wyndow"},
  {"placename_id":31532,"placename":"'Change"},
  {"placename_id":31533,"placename":"Father Thames"},
  {"placename_id":31534,"placename":"Pimlico"},
  {"placename_id":31535,"placename":"Battersea Bridge"},
  {"placename_id":31536,"placename":"Houses of Parliament"},
  {"placename_id":31537,"placename":"Brompton"},
  {"placename_id":31538,"placename":"Belgravia"},
  {"placename_id":31539,"placename":"Camberling Town"},
  {"placename_id":31540,"placename":"Mile End Road"},
  {"placename_id":31541,"placename":"Buckingham Palace"},
  {"placename_id":31542,"placename":"Ebury Street"},
  {"placename_id":31543,"placename":"Princes' Gardens"},
  {"placename_id":31546,"placename":"Mapledurham"},
  {"placename_id":31547,"placename":"riverside"},
  {"placename_id":31551,"placename":"Malta Street"},
  {"placename_id":31552,"placename":"Waterloo Station"},
  {"placename_id":31553,"placename":"Old Church"},
  {"placename_id":31554,"placename":"Cork St"},
  {"placename_id":31555,"placename":"Hamilton Place"},
  {"placename_id":31556,"placename":"Green Hotel"},
  {"placename_id":31557,"placename":"Crown and Sceptre"},
  {"placename_id":31558,"placename":"Budge Row"},
  {"placename_id":31559,"placename":"Putney Bridge"},
  {"placename_id":31560,"placename":"Wood Street, Cheapside"},
  {"placename_id":31561,"placename":"Little Britain"},
  {"placename_id":31562,"placename":"Walworth"},
  {"placename_id":31563,"placename":"Euston Station"},
  {"placename_id":31564,"placename":"Senate House"},
  {"placename_id":31565,"placename":"Hanover Terrace"},
  {"placename_id":31566,"placename":"Poetry Bookshop"},
  {"placename_id":31567,"placename":"Fanchurch Street"},
  {"placename_id":31568,"placename":"Moorefields"},
  {"placename_id":31569,"placename":"White Hall"},
  {"placename_id":31570,"placename":"the dirty Thames"},
  {"placename_id":31571,"placename":"Marybone"},
  {"placename_id":31572,"placename":"Pancrass"},
  {"placename_id":31573,"placename":"Kentish Town"},
  {"placename_id":31576,"placename":"Lambeths"},
  {"placename_id":31578,"placename":"Woolwichleagues"},
  {"placename_id":31579,"placename":"Eastchept"},
  {"placename_id":31580,"placename":"Marrowbone"},
  {"placename_id":31581,"placename":"Newgade"},
  {"placename_id":31582,"placename":"Threadneedles"},
  {"placename_id":31583,"placename":"sevendialled"},
  {"placename_id":31584,"placename":"Norwood"},
  {"placename_id":31585,"placename":"Euston"},
  {"placename_id":31586,"placename":"Stepney"},
  {"placename_id":31587,"placename":"Southwalk"},
  {"placename_id":31588,"placename":"hide park"},
  {"placename_id":31591,"placename":"Sewell Street"},
  {"placename_id":35001,"placename":"Fetter lane"},
  {"placename_id":35007,"placename":"Clerkenwell"},
  {"placename_id":35009,"placename":"Tottenham"},
  {"placename_id":35016,"placename":"St James's"},
  {"placename_id":35017,"placename":"Drury-lane"},
  {"placename_id":35036,"placename":"Ludgate"},
  {"placename_id":35038,"placename":"Lisson Grove"},
  {"placename_id":35042,"placename":"Saint Paul's"},
  {"placename_id":35054,"placename":"Fish Street"},
  {"placename_id":35055,"placename":"Charing-Cross"},
  {"placename_id":35062,"placename":"Aldgate"},
  {"placename_id":35064,"placename":"Cripplegate"},
  {"placename_id":35067,"placename":"Deptford"},
  {"placename_id":35071,"placename":"Guildhall"},
  {"placename_id":35073,"placename":"St. Dunstan's"},
  {"placename_id":35075,"placename":"King-street"},
  {"placename_id":35077,"placename":"Chancery Row"},
  {"placename_id":35078,"placename":"Marke-lane"},
  {"placename_id":35079,"placename":"Fish-street"},
  {"placename_id":35080,"placename":"Pudding-lane"},
  {"placename_id":35081,"placename":"Steeleyard"},
  {"placename_id":35083,"placename":"Thames-street"},
  {"placename_id":35084,"placename":"Dowgate"},
  {"placename_id":35085,"placename":"Canning-streets"},
  {"placename_id":35086,"placename":"Bankside"},
  {"placename_id":35087,"placename":"Fish-streets"},
  {"placename_id":35088,"placename":"Bethnal Green"},
  {"placename_id":35090,"placename":"Tower-streete"},
  {"placename_id":35091,"placename":"Tower-street"},
  {"placename_id":35092,"placename":"Trinity"},
  {"placename_id":35093,"placename":"Fleete-streete"},
  {"placename_id":35094,"placename":"Barking"},
  {"placename_id":35095,"placename":"City"},
  {"placename_id":35096,"placename":"Fenchurch Street"},
  {"placename_id":35097,"placename":"Lombard Street"},
  {"placename_id":35100,"placename":"Bishop's- gate"},
  {"placename_id":35101,"placename":"Southwarke"},
  {"placename_id":35103,"placename":"Leadenhall"},
  {"placename_id":35104,"placename":"Mile-end"},
  {"placename_id":35105,"placename":"Tower-hill"},
  {"placename_id":35106,"placename":"Aldersgate"},
  {"placename_id":35110,"placename":"the westering Thames"},
  {"placename_id":35112,"placename":"Spitalfields"},
  {"placename_id":35115,"placename":"the sweet, tranquil Thames"},
  {"placename_id":35116,"placename":"St Pauls"},
  {"placename_id":35117,"placename":"Thames waters"},
  {"placename_id":35118,"placename":"Inner Temple"},
  {"placename_id":35121,"placename":"Newgate's"},
  {"placename_id":35123,"placename":"Chiswick"},
  {"placename_id":35124,"placename":"Chislehurst"},
  {"placename_id":35125,"placename":"Zoological Gardens"},
  {"placename_id":35126,"placename":"Royal Academy"},
  {"placename_id":35130,"placename":"Denmark Hill"},
  {"placename_id":35133,"placename":"Thames Ditton"},
  {"placename_id":35138,"placename":"Regent-Street"},
  {"placename_id":35139,"placename":"Bucklersbury"},
  {"placename_id":35140,"placename":"Harrow"},
  {"placename_id":35141,"placename":"East-cheap"},
  {"placename_id":35143,"placename":"Monmouth Street"},
  {"placename_id":35144,"placename":"Cock Lane"},
  {"placename_id":35150,"placename":"Euston Square"},
  {"placename_id":35151,"placename":"St. Pancras"},
  {"placename_id":35152,"placename":"Somers Town"},
  {"placename_id":35153,"placename":"India House"},
  {"placename_id":35155,"placename":"Blackfriars Road"},
  {"placename_id":35156,"placename":"Blackheath"},
  {"placename_id":35159,"placename":"Change Alley"},
  {"placename_id":35160,"placename":"Change-Alley"},
  {"placename_id":35161,"placename":"Lincoln’s Inn Fields"},
  {"placename_id":35162,"placename":"St. Paul’s"},
  {"placename_id":35163,"placename":"Villiers Street"},
  {"placename_id":35165,"placename":"Cornhill"},
  {"placename_id":35166,"placename":"Barbican"},
  {"placename_id":35167,"placename":"city of London"},
  {"placename_id":35168,"placename":"the Monument"},
  {"placename_id":35173,"placename":"Putney"},
  {"placename_id":35175,"placename":"Richmond Bridge"},
  {"placename_id":35176,"placename":"Blackfriar's"},
  {"placename_id":35180,"placename":"Sydenham"},
  {"placename_id":35186,"placename":"Wimbledon Common"},
  {"placename_id":35189,"placename":"Dulwich"},
  {"placename_id":35191,"placename":"Streatham"},
  {"placename_id":35192,"placename":"Tooting"},
  {"placename_id":35193,"placename":"St. James's Hall"},
  {"placename_id":35195,"placename":"Kilburn"},
  {"placename_id":35198,"placename":"Finchley"},
  {"placename_id":35199,"placename":"Bromley"},
  {"placename_id":35204,"placename":"Somers' Town"},
  {"placename_id":35205,"placename":"Gray's-Inn"},
  {"placename_id":35206,"placename":"St. John's Gate"},
  {"placename_id":35207,"placename":"Watling-street"},
  {"placename_id":35208,"placename":"Caledonian"},
  {"placename_id":35212,"placename":"Kingston-upon-Thames"},
  {"placename_id":35213,"placename":"banks of Thames"},
  {"placename_id":35216,"placename":"Norwood Hill"},
  {"placename_id":35217,"placename":"St. Stephen's"},
  {"placename_id":35220,"placename":"Croydon"},
  {"placename_id":35221,"placename":"Brixton"},
  {"placename_id":35222,"placename":"East Ham"},
  {"placename_id":35224,"placename":"east-end"},
  {"placename_id":35226,"placename":"Kingston-on-Thames"},
  {"placename_id":35227,"placename":"Westminster Cathedral"},
  {"placename_id":35229,"placename":"Walthamstow"},
  {"placename_id":35231,"placename":"Cannon Street"},
  {"placename_id":35236,"placename":"St Martin's Lane"},
  {"placename_id":35238,"placename":"Mile- / End"},
  {"placename_id":35244,"placename":"St. Bartholomew's Hospital"},
  {"placename_id":35245,"placename":"the placid Thames"},
  {"placename_id":35246,"placename":"Minories"},
  {"placename_id":35249,"placename":"Inner-Temple"},
  {"placename_id":35251,"placename":"Poland Street"},
  {"placename_id":35252,"placename":"Holloway"},
  {"placename_id":35253,"placename":"Camden"},
  {"placename_id":35254,"placename":"Shoreditch"},
  {"placename_id":35255,"placename":"Edmonton"},
  {"placename_id":35256,"placename":"Roehampton"},
  {"placename_id":35258,"placename":"St. Giles"},
  {"placename_id":35260,"placename":"Harley Street"},
  {"placename_id":35261,"placename":"May Fair"},
  {"placename_id":35264,"placename":"Tabard inn"},
  {"placename_id":35265,"placename":"The Tower showed"},
  {"placename_id":35266,"placename":"Pudding Lane"},
  {"placename_id":35267,"placename":"Marlborough House"},
  {"placename_id":35268,"placename":"Kennington Oval"},
  {"placename_id":35269,"placename":"Mincing Lane"},
  {"placename_id":35270,"placename":"East Cheap"},
  {"placename_id":35271,"placename":"Charing"},
  {"placename_id":35272,"placename":"Farringdon"},
  {"placename_id":35273,"placename":"Southwark Bridge"},
  {"placename_id":35274,"placename":"Walbrook"},
  {"placename_id":35275,"placename":"Barge Yard"},
  {"placename_id":35276,"placename":"Old Jewry"},
  {"placename_id":35277,"placename":"Whitefriars Club"},
  {"placename_id":35278,"placename":"Wellington"},
  {"placename_id":35279,"placename":"Nelson monuments"},
  {"placename_id":35280,"placename":"Albert memorial"},
  {"placename_id":35281,"placename":"Pall-Mall"},
  {"placename_id":35282,"placename":"Bedford Park"},
  {"placename_id":35283,"placename":"Kelmscott House"},
  {"placename_id":35285,"placename":"Holland Park"},
  {"placename_id":35286,"placename":"Queen's Square"},
  {"placename_id":35287,"placename":"Fitzroy Road"},
  {"placename_id":35288,"placename":"Burnham Beeches"},
  {"placename_id":35290,"placename":"Farnham Royal"},
  {"placename_id":35291,"placename":"North End"},
  {"placename_id":35293,"placename":"Holland House"},
  {"placename_id":35294,"placename":"Coomb Wood"},
  {"placename_id":35295,"placename":"Forest Hill"},
  {"placename_id":35296,"placename":"Dean Street"},
  {"placename_id":35298,"placename":"Mortlake"},
  {"placename_id":35299,"placename":"College Green"},
  {"placename_id":35300,"placename":"Jubilee"},
  {"placename_id":35301,"placename":"Brook Green"},
  {"placename_id":35304,"placename":"river Thames"},
  {"placename_id":35307,"placename":"Borough"},
  {"placename_id":35308,"placename":"St. George's Fields"},
  {"placename_id":35309,"placename":"Queen Street"},
  {"placename_id":35310,"placename":"Butcher Row"},
  {"placename_id":35311,"placename":"Chatham"},
  {"placename_id":35312,"placename":"Brockley"},
  {"placename_id":35313,"placename":"the pale green Thames"},
  {"placename_id":35315,"placename":"Clapham Junction"},
  {"placename_id":35316,"placename":"Bedford Square"},
  {"placename_id":35320,"placename":"Long Acre"},
  {"placename_id":35322,"placename":"Shepherd's Bush"},
  {"placename_id":35324,"placename":"Haverstock"},
  {"placename_id":35326,"placename":"Shaftesbury"},
  {"placename_id":35331,"placename":"KEW GARDENS"},
  {"placename_id":35332,"placename":"London Library"},
  {"placename_id":35333,"placename":"Tower Bridge"},
  {"placename_id":35335,"placename":"Grosvenor"},
  {"placename_id":35336,"placename":"Thames bank"},
  {"placename_id":35337,"placename":"Campden"},
  {"placename_id":35338,"placename":"Primrose"},
  {"placename_id":35339,"placename":"Edgware"},
  {"placename_id":35340,"placename":"Victoria Street"},
  {"placename_id":35341,"placename":"Regent’s Park"},
  {"placename_id":35342,"placename":"Finsbury"},
  {"placename_id":35346,"placename":"Muswell Hill"},
  {"placename_id":35347,"placename":"Calendonian"},
  {"placename_id":35350,"placename":"Monument"},
  {"placename_id":35351,"placename":"the Thames embankment"},
  {"placename_id":35352,"placename":"House of Commons"},
  {"placename_id":35353,"placename":"Elephant and Castle"},
  {"placename_id":35354,"placename":"Inner-Temple-lane"},
  {"placename_id":35355,"placename":"the Temple-stairs"},
  {"placename_id":35356,"placename":"the Temple station"},
  {"placename_id":35357,"placename":"Tower of London"},
  {"placename_id":35358,"placename":"Whitehall Court"},
  {"placename_id":35359,"placename":"Hyde Park Gate"},
  {"placename_id":35360,"placename":"Bloomsbury Square"},
  {"placename_id":35361,"placename":"Kensington Station"}

])
